name: Commit Stage
on: push

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ificu/admin-eam-front
  VERSION: latest

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Valid Check
        run: npm ci
      
  package:
    name: Package and Publish
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [ build ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      security-events: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Get current date
        run: echo "TAG_DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY}}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}        
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY}}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}  
            ${{ env.REGISTRY}}/${{ env.IMAGE_NAME }}:${{ env.TAG_DATE }}          


    
